#!/bin/bash

docker build -f $(pwd)/Dockerfile -t rivero/mqtt-explorer-web .
docker tag rivero/mqtt-explorer-web registry.raulrivero.int:5000/rivero/mqtt-explorer-web
docker push registry.raulrivero.int:5000/rivero/mqtt-explorer-web

echo 'Ahora podrias ejecutar:'
echo '-----'
echo 'docker run --rm -d --name mqtt-explorer-web -p 8080:80  rivero/mqtt-explorer-web'
echo 'docker exec -it mqtt-explorer-web  /bin/bash'
echo '-----'
